version: '3.7'

services:
  app:
    volumes:
      - static:/static
    env_file:
      - .venv
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - app
  redis:
    image: redis:6
    container_name: app_local_redis
    ports:
      - "6379:6379"


volumes:
  static:
