# Generated by Django 3.2.13 on 2022-06-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_quote_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_text_json',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON text'),
        ),
    ]
