# Generated by Django 3.2.13 on 2022-07-10 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_alter_quote_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('hye', 'Armenian'), ('rus', 'Russian'), ('fra', 'French'), ('hin', 'Hindi')], default='eng', max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_file',
            field=models.ImageField(blank=True, null=True, upload_to='upload', validators=[django.core.validators.validate_image_file_extension, django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])], verbose_name='Quote'),
        ),
    ]
